### PR TITLE
Fix more ambiguity

### PR DESCRIPTION
**Pull request by avik-pal**
Needed for https://github.com/SciML/DiffEqFlux.jl/pull/873

The ambiguity doesn't exist in 1.9 for some reason (see the test failures)

### CODE REVIEW

**Comment by mcabbott** [comment]
This and #152 really ought to have tests which fail before.

**Comment by avik-pal** [comment]
See the nightly failures 

1. Before anything https://github.com/FluxML/Tracker.jl/actions/runs/6680164353/job/18153013597#step:6:2155 (31 failures)
2. After #152 https://github.com/FluxML/Tracker.jl/actions/runs/6804974552/job/18503603419#step:6:721 (11 failures)
3. Now https://github.com/FluxML/Tracker.jl/actions/runs/6828259970/job/18572049061?pr=154#step:6:647 (9 failures)

Not sure what changed in 1.10 which started these ambiguity failures

**Comment by avik-pal** [comment]
@mcabbott @ChrisRackauckas All the nightly ambiguity failures are gone with these changes

**Comment by avik-pal** [comment]
1.10+ tests fail on master https://github.com/FluxML/Tracker.jl/pull/155

**Review by ChrisRackauckas — APPROVED** [review]
Confirmed this fixes the broken tests

**Pull request merged**
