### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fixing compat bounds impeding tagging (https://github.com/JuliaRegistries/General/pull/25139)

### CODE REVIEW

**Comment by devmotion** [comment]
@CarloLucibello It would be great to get this fix into Tracker and release a new version. As long as Tracker is not compatible with SpecialFunctions 1, our tests in the Turing ecosystem won't actually run with SpecialFunctions 1 and we can't be sure that compat updates don't break anything. I just ran the tests locally successfully with your compat bounds on Julia 1.3, so maybe some dependencies were updated and it is sufficient to rerun the tests here?

**Comment by CarloLucibello** [comment]
let's try, then I'll need @DhairyaLGandhi to merge this, I don't have write acces in this repo

**Comment by devmotion** [comment]
Ah wait, I just saw that Tracker has a Manifest.toml checked in. I guess I updated that one.

**Comment by CarloLucibello** [comment]
n-th time I see a Manifest induced problem, I'll remove and .gitignore it

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by CarloLucibello** [comment]
@ChrisRackauckas could you tag a release? version is already bumped

**Pull request merged**
