### PR TITLE
Bump Adapt

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
supersedes #66

### CODE REVIEW

**Comment by devmotion** [comment]
It seems Adapt 2 also breaks downstream packages such as Bijectors. Would it be possible to make a bugfix release which is only compatible with Adapt 1 and/or change the bounds in the registry if it takes more time to fix compatibility with Adapt 2?

**Comment by DhairyaLGandhi** [comment]
I think the Adapt issue is just https://github.com/JuliaGPU/Adapt.jl/issues/24.

Happy to make a bugfix release but hopefully the adapt fix wouldn't take very long

**Comment by devmotion** [comment]
Maybe it might be even better to fix https://github.com/JuliaRegistries/General/blob/226d40a90a66e1f947f241363ef607068030f254/T/Tracker/Compat.toml#L45 since it seems Tracker 0.2.7 shouldn't be declared to be compatible with Adapt 2?

**Comment by devmotion** [comment]
The fix in Adapt fixed the issues in Bijectors, so there's no need for any bugfix releases or other fixes in Tracker from my side any more. Thanks for tracking down the issue so quickly!

**Pull request closed without merging**
